package com.siebel.asi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-05T13:57:34.419+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://siebel.com/asi/", name = "Default")
@XmlSeeAlso({com.siebel.xml.order_20interface.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Default {

    @WebMethod(operationName = "TMCVCPOTCOrderInsertOrUpdate", action = "document/http://siebel.com/asi/:TMCVCPOTCOrderInsertOrUpdate")
    @WebResult(name = "TMCVCPOTCOrderInsertOrUpdate_Output", targetNamespace = "http://siebel.com/asi/", partName = "TMCVCPOTCOrderInsertOrUpdate_Output")
    public TMCVCPOTCOrderInsertOrUpdateOutput tmcvcpotcOrderInsertOrUpdate(
        @WebParam(partName = "TMCVCPOTCOrderInsertOrUpdate_Input", name = "TMCVCPOTCOrderInsertOrUpdate_Input", targetNamespace = "http://siebel.com/asi/")
        TMCVCPOTCOrderInsertOrUpdateInput tmcvcpotcOrderInsertOrUpdateInput
    );
}
